<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Hangfire.Core" Version="1.8.15" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Cve.Net.Search.Domain.Database\Cve.Net.Search.Domain.Database.csproj" />
  </ItemGroup>
</Project>