//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://capec.mitre.org/capec-3", IsNullable=false)]
public class Attack_Pattern_Catalog {
    
    private AttackPatternType[] attack_PatternsField;
    
    private CategoryType[] categoriesField;
    
    private ViewType[] viewsField;
    
    private ExternalReferenceType[] external_ReferencesField;
    
    private string nameField;
    
    private string versionField;
    
    private System.DateTime dateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Attack_Pattern", IsNullable=false)]
    public AttackPatternType[] Attack_Patterns {
        get {
            return this.attack_PatternsField;
        }
        set {
            this.attack_PatternsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Category", IsNullable=false)]
    public CategoryType[] Categories {
        get {
            return this.categoriesField;
        }
        set {
            this.categoriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("View", IsNullable=false)]
    public ViewType[] Views {
        get {
            return this.viewsField;
        }
        set {
            this.viewsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("External_Reference", IsNullable=false)]
    public ExternalReferenceType[] External_References {
        get {
            return this.external_ReferencesField;
        }
        set {
            this.external_ReferencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public class AttackPatternType {
    
    private StructuredTextType descriptionField;
    
    private StructuredTextType extended_DescriptionField;
    
    private AlternateTermsTypeAlternate_Term[] alternate_TermsField;
    
    private LikelihoodEnumeration likelihood_Of_AttackField;
    
    private bool likelihood_Of_AttackFieldSpecified;
    
    private SeverityEnumeration typical_SeverityField;
    
    private bool typical_SeverityFieldSpecified;
    
    private RelatedAttackPatternTypeRelated_Attack_Pattern[] related_Attack_PatternsField;
    
    private ExecutionFlowTypeAttack_Step[] execution_FlowField;
    
    private StructuredTextType[] prerequisitesField;
    
    private SkillsTypeSkill[] skills_RequiredField;
    
    private StructuredTextType[] resources_RequiredField;
    
    private StructuredTextType[] indicatorsField;
    
    private ConsequencesTypeConsequence[] consequencesField;
    
    private StructuredTextType[] mitigationsField;
    
    private StructuredTextType[] example_InstancesField;
    
    private RelatedWeaknessesTypeRelated_Weakness[] related_WeaknessesField;
    
    private TaxonomyMappingsTypeTaxonomy_Mapping[] taxonomy_MappingsField;
    
    private ReferencesTypeReference[] referencesField;
    
    private NotesTypeNote[] notesField;
    
    private ContentHistoryType content_HistoryField;
    
    private string idField;
    
    private string nameField;
    
    private AbstractionEnumeration abstractionField;
    
    private StatusEnumeration statusField;
    
    /// <remarks/>
    public StructuredTextType Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public StructuredTextType Extended_Description {
        get {
            return this.extended_DescriptionField;
        }
        set {
            this.extended_DescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Alternate_Term", IsNullable=false)]
    public AlternateTermsTypeAlternate_Term[] Alternate_Terms {
        get {
            return this.alternate_TermsField;
        }
        set {
            this.alternate_TermsField = value;
        }
    }
    
    /// <remarks/>
    public LikelihoodEnumeration Likelihood_Of_Attack {
        get {
            return this.likelihood_Of_AttackField;
        }
        set {
            this.likelihood_Of_AttackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Likelihood_Of_AttackSpecified {
        get {
            return this.likelihood_Of_AttackFieldSpecified;
        }
        set {
            this.likelihood_Of_AttackFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public SeverityEnumeration Typical_Severity {
        get {
            return this.typical_SeverityField;
        }
        set {
            this.typical_SeverityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Typical_SeveritySpecified {
        get {
            return this.typical_SeverityFieldSpecified;
        }
        set {
            this.typical_SeverityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Related_Attack_Pattern", IsNullable=false)]
    public RelatedAttackPatternTypeRelated_Attack_Pattern[] Related_Attack_Patterns {
        get {
            return this.related_Attack_PatternsField;
        }
        set {
            this.related_Attack_PatternsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Attack_Step", IsNullable=false)]
    public ExecutionFlowTypeAttack_Step[] Execution_Flow {
        get {
            return this.execution_FlowField;
        }
        set {
            this.execution_FlowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Prerequisite", IsNullable=false)]
    public StructuredTextType[] Prerequisites {
        get {
            return this.prerequisitesField;
        }
        set {
            this.prerequisitesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Skill", IsNullable=false)]
    public SkillsTypeSkill[] Skills_Required {
        get {
            return this.skills_RequiredField;
        }
        set {
            this.skills_RequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Resource", IsNullable=false)]
    public StructuredTextType[] Resources_Required {
        get {
            return this.resources_RequiredField;
        }
        set {
            this.resources_RequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Indicator", IsNullable=false)]
    public StructuredTextType[] Indicators {
        get {
            return this.indicatorsField;
        }
        set {
            this.indicatorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Consequence", IsNullable=false)]
    public ConsequencesTypeConsequence[] Consequences {
        get {
            return this.consequencesField;
        }
        set {
            this.consequencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Mitigation", IsNullable=false)]
    public StructuredTextType[] Mitigations {
        get {
            return this.mitigationsField;
        }
        set {
            this.mitigationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Example", IsNullable=false)]
    public StructuredTextType[] Example_Instances {
        get {
            return this.example_InstancesField;
        }
        set {
            this.example_InstancesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Related_Weakness", IsNullable=false)]
    public RelatedWeaknessesTypeRelated_Weakness[] Related_Weaknesses {
        get {
            return this.related_WeaknessesField;
        }
        set {
            this.related_WeaknessesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Taxonomy_Mapping", IsNullable=false)]
    public TaxonomyMappingsTypeTaxonomy_Mapping[] Taxonomy_Mappings {
        get {
            return this.taxonomy_MappingsField;
        }
        set {
            this.taxonomy_MappingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Reference", IsNullable=false)]
    public ReferencesTypeReference[] References {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Note", IsNullable=false)]
    public NotesTypeNote[] Notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    public ContentHistoryType Content_History {
        get {
            return this.content_HistoryField;
        }
        set {
            this.content_HistoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AbstractionEnumeration Abstraction {
        get {
            return this.abstractionField;
        }
        set {
            this.abstractionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public StatusEnumeration Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public class StructuredTextType {
    
    private System.Xml.XmlNode[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public class ExternalReferenceType {
    
    private string[] authorField;
    
    private string titleField;
    
    private string editionField;
    
    private string publicationField;
    
    private string publication_YearField;
    
    private string publication_MonthField;
    
    private string publication_DayField;
    
    private string publisherField;
    
    private string uRLField;
    
    private System.DateTime uRL_DateField;
    
    private bool uRL_DateFieldSpecified;
    
    private string reference_IDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Author")]
    public string[] Author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string Edition {
        get {
            return this.editionField;
        }
        set {
            this.editionField = value;
        }
    }
    
    /// <remarks/>
    public string Publication {
        get {
            return this.publicationField;
        }
        set {
            this.publicationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
    public string Publication_Year {
        get {
            return this.publication_YearField;
        }
        set {
            this.publication_YearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gMonth")]
    public string Publication_Month {
        get {
            return this.publication_MonthField;
        }
        set {
            this.publication_MonthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gDay")]
    public string Publication_Day {
        get {
            return this.publication_DayField;
        }
        set {
            this.publication_DayField = value;
        }
    }
    
    /// <remarks/>
    public string Publisher {
        get {
            return this.publisherField;
        }
        set {
            this.publisherField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string URL {
        get {
            return this.uRLField;
        }
        set {
            this.uRLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime URL_Date {
        get {
            return this.uRL_DateField;
        }
        set {
            this.uRL_DateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool URL_DateSpecified {
        get {
            return this.uRL_DateFieldSpecified;
        }
        set {
            this.uRL_DateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Reference_ID {
        get {
            return this.reference_IDField;
        }
        set {
            this.reference_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public class ViewType {
    
    private StructuredTextType objectiveField;
    
    private AudienceTypeStakeholder[] audienceField;
    
    private RelationshipsType membersField;
    
    private string filterField;
    
    private ReferencesTypeReference[] referencesField;
    
    private NotesTypeNote[] notesField;
    
    private ContentHistoryType content_HistoryField;
    
    private string idField;
    
    private string nameField;
    
    private ViewTypeEnumeration typeField;
    
    private StatusEnumeration statusField;
    
    /// <remarks/>
    public StructuredTextType Objective {
        get {
            return this.objectiveField;
        }
        set {
            this.objectiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Stakeholder", IsNullable=false)]
    public AudienceTypeStakeholder[] Audience {
        get {
            return this.audienceField;
        }
        set {
            this.audienceField = value;
        }
    }
    
    /// <remarks/>
    public RelationshipsType Members {
        get {
            return this.membersField;
        }
        set {
            this.membersField = value;
        }
    }
    
    /// <remarks/>
    public string Filter {
        get {
            return this.filterField;
        }
        set {
            this.filterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Reference", IsNullable=false)]
    public ReferencesTypeReference[] References {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Note", IsNullable=false)]
    public NotesTypeNote[] Notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    public ContentHistoryType Content_History {
        get {
            return this.content_HistoryField;
        }
        set {
            this.content_HistoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ViewTypeEnumeration Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public StatusEnumeration Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class AudienceTypeStakeholder {
    
    private StakeholderEnumeration typeField;
    
    private StructuredTextType descriptionField;
    
    /// <remarks/>
    public StakeholderEnumeration Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public StructuredTextType Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum StakeholderEnumeration {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Academic Researchers")]
    AcademicResearchers,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Applied Researchers")]
    AppliedResearchers,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Assessment Customers")]
    AssessmentCustomers,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Assessment Vendors")]
    AssessmentVendors,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("CAPEC Team")]
    CAPECTeam,
    
    /// <remarks/>
    Educators,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Information Providers")]
    InformationProviders,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Software Customers")]
    SoftwareCustomers,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Software Designers")]
    SoftwareDesigners,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Software Developers")]
    SoftwareDevelopers,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Software Vendors")]
    SoftwareVendors,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public class RelationshipsType {
    
    private RelationshipsTypeMember_Of[] member_OfField;
    
    private RelationshipsTypeHas_Member[] has_MemberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Member_Of")]
    public RelationshipsTypeMember_Of[] Member_Of {
        get {
            return this.member_OfField;
        }
        set {
            this.member_OfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Has_Member")]
    public RelationshipsTypeHas_Member[] Has_Member {
        get {
            return this.has_MemberField;
        }
        set {
            this.has_MemberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class RelationshipsTypeMember_Of {
    
    private ExcludeRelatedType[] exclude_RelatedField;
    
    private string cAPEC_IDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Exclude_Related")]
    public ExcludeRelatedType[] Exclude_Related {
        get {
            return this.exclude_RelatedField;
        }
        set {
            this.exclude_RelatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string CAPEC_ID {
        get {
            return this.cAPEC_IDField;
        }
        set {
            this.cAPEC_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public class ExcludeRelatedType {
    
    private string exclude_IDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Exclude_ID {
        get {
            return this.exclude_IDField;
        }
        set {
            this.exclude_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class RelationshipsTypeHas_Member {
    
    private ExcludeRelatedType[] exclude_RelatedField;
    
    private string cAPEC_IDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Exclude_Related")]
    public ExcludeRelatedType[] Exclude_Related {
        get {
            return this.exclude_RelatedField;
        }
        set {
            this.exclude_RelatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string CAPEC_ID {
        get {
            return this.cAPEC_IDField;
        }
        set {
            this.cAPEC_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class ReferencesTypeReference {
    
    private string external_Reference_IDField;
    
    private string sectionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string External_Reference_ID {
        get {
            return this.external_Reference_IDField;
        }
        set {
            this.external_Reference_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Section {
        get {
            return this.sectionField;
        }
        set {
            this.sectionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class NotesTypeNote : StructuredTextType {
    
    private NoteTypeEnumeration typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public NoteTypeEnumeration Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum NoteTypeEnumeration {
    
    /// <remarks/>
    Maintenance,
    
    /// <remarks/>
    Relationship,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Research Gap")]
    ResearchGap,
    
    /// <remarks/>
    Terminology,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public class ContentHistoryType {
    
    private ContentHistoryTypeSubmission submissionField;
    
    private ContentHistoryTypeModification[] modificationField;
    
    private ContentHistoryTypeContribution[] contributionField;
    
    private ContentHistoryTypePrevious_Entry_Name[] previous_Entry_NameField;
    
    /// <remarks/>
    public ContentHistoryTypeSubmission Submission {
        get {
            return this.submissionField;
        }
        set {
            this.submissionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Modification")]
    public ContentHistoryTypeModification[] Modification {
        get {
            return this.modificationField;
        }
        set {
            this.modificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Contribution")]
    public ContentHistoryTypeContribution[] Contribution {
        get {
            return this.contributionField;
        }
        set {
            this.contributionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Previous_Entry_Name")]
    public ContentHistoryTypePrevious_Entry_Name[] Previous_Entry_Name {
        get {
            return this.previous_Entry_NameField;
        }
        set {
            this.previous_Entry_NameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class ContentHistoryTypeSubmission {
    
    private string submission_NameField;
    
    private string submission_OrganizationField;
    
    private System.DateTime submission_DateField;
    
    private bool submission_DateFieldSpecified;
    
    private string submission_CommentField;
    
    /// <remarks/>
    public string Submission_Name {
        get {
            return this.submission_NameField;
        }
        set {
            this.submission_NameField = value;
        }
    }
    
    /// <remarks/>
    public string Submission_Organization {
        get {
            return this.submission_OrganizationField;
        }
        set {
            this.submission_OrganizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Submission_Date {
        get {
            return this.submission_DateField;
        }
        set {
            this.submission_DateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Submission_DateSpecified {
        get {
            return this.submission_DateFieldSpecified;
        }
        set {
            this.submission_DateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Submission_Comment {
        get {
            return this.submission_CommentField;
        }
        set {
            this.submission_CommentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class ContentHistoryTypeModification {
    
    private string modification_NameField;
    
    private string modification_OrganizationField;
    
    private System.DateTime modification_DateField;
    
    private bool modification_DateFieldSpecified;
    
    private ImportanceEnumeration modification_ImportanceField;
    
    private bool modification_ImportanceFieldSpecified;
    
    private string modification_CommentField;
    
    /// <remarks/>
    public string Modification_Name {
        get {
            return this.modification_NameField;
        }
        set {
            this.modification_NameField = value;
        }
    }
    
    /// <remarks/>
    public string Modification_Organization {
        get {
            return this.modification_OrganizationField;
        }
        set {
            this.modification_OrganizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Modification_Date {
        get {
            return this.modification_DateField;
        }
        set {
            this.modification_DateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Modification_DateSpecified {
        get {
            return this.modification_DateFieldSpecified;
        }
        set {
            this.modification_DateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ImportanceEnumeration Modification_Importance {
        get {
            return this.modification_ImportanceField;
        }
        set {
            this.modification_ImportanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Modification_ImportanceSpecified {
        get {
            return this.modification_ImportanceFieldSpecified;
        }
        set {
            this.modification_ImportanceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Modification_Comment {
        get {
            return this.modification_CommentField;
        }
        set {
            this.modification_CommentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum ImportanceEnumeration {
    
    /// <remarks/>
    Normal,
    
    /// <remarks/>
    Critical,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class ContentHistoryTypeContribution {
    
    private string contribution_NameField;
    
    private string contribution_OrganizationField;
    
    private System.DateTime contribution_DateField;
    
    private bool contribution_DateFieldSpecified;
    
    private string contribution_CommentField;
    
    private ContentHistoryTypeContributionType typeField;
    
    /// <remarks/>
    public string Contribution_Name {
        get {
            return this.contribution_NameField;
        }
        set {
            this.contribution_NameField = value;
        }
    }
    
    /// <remarks/>
    public string Contribution_Organization {
        get {
            return this.contribution_OrganizationField;
        }
        set {
            this.contribution_OrganizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Contribution_Date {
        get {
            return this.contribution_DateField;
        }
        set {
            this.contribution_DateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Contribution_DateSpecified {
        get {
            return this.contribution_DateFieldSpecified;
        }
        set {
            this.contribution_DateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Contribution_Comment {
        get {
            return this.contribution_CommentField;
        }
        set {
            this.contribution_CommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ContentHistoryTypeContributionType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public enum ContentHistoryTypeContributionType {
    
    /// <remarks/>
    Content,
    
    /// <remarks/>
    Feedback,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class ContentHistoryTypePrevious_Entry_Name {
    
    private System.DateTime dateField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum ViewTypeEnumeration {
    
    /// <remarks/>
    Implicit,
    
    /// <remarks/>
    Explicit,
    
    /// <remarks/>
    Graph,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum StatusEnumeration {
    
    /// <remarks/>
    Deprecated,
    
    /// <remarks/>
    Draft,
    
    /// <remarks/>
    Incomplete,
    
    /// <remarks/>
    Obsolete,
    
    /// <remarks/>
    Stable,
    
    /// <remarks/>
    Usable,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public class CategoryType {
    
    private StructuredTextType summaryField;
    
    private RelationshipsType relationshipsField;
    
    private TaxonomyMappingsTypeTaxonomy_Mapping[] taxonomy_MappingsField;
    
    private ReferencesTypeReference[] referencesField;
    
    private NotesTypeNote[] notesField;
    
    private ContentHistoryType content_HistoryField;
    
    private string idField;
    
    private string nameField;
    
    private StatusEnumeration statusField;
    
    /// <remarks/>
    public StructuredTextType Summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    public RelationshipsType Relationships {
        get {
            return this.relationshipsField;
        }
        set {
            this.relationshipsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Taxonomy_Mapping", IsNullable=false)]
    public TaxonomyMappingsTypeTaxonomy_Mapping[] Taxonomy_Mappings {
        get {
            return this.taxonomy_MappingsField;
        }
        set {
            this.taxonomy_MappingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Reference", IsNullable=false)]
    public ReferencesTypeReference[] References {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Note", IsNullable=false)]
    public NotesTypeNote[] Notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    public ContentHistoryType Content_History {
        get {
            return this.content_HistoryField;
        }
        set {
            this.content_HistoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public StatusEnumeration Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class TaxonomyMappingsTypeTaxonomy_Mapping {
    
    private string entry_IDField;
    
    private string entry_NameField;
    
    private TaxonomyMappingFitEnumeration mapping_FitField;
    
    private bool mapping_FitFieldSpecified;
    
    private TaxonomyNameEnumeration taxonomy_NameField;
    
    /// <remarks/>
    public string Entry_ID {
        get {
            return this.entry_IDField;
        }
        set {
            this.entry_IDField = value;
        }
    }
    
    /// <remarks/>
    public string Entry_Name {
        get {
            return this.entry_NameField;
        }
        set {
            this.entry_NameField = value;
        }
    }
    
    /// <remarks/>
    public TaxonomyMappingFitEnumeration Mapping_Fit {
        get {
            return this.mapping_FitField;
        }
        set {
            this.mapping_FitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Mapping_FitSpecified {
        get {
            return this.mapping_FitFieldSpecified;
        }
        set {
            this.mapping_FitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TaxonomyNameEnumeration Taxonomy_Name {
        get {
            return this.taxonomy_NameField;
        }
        set {
            this.taxonomy_NameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum TaxonomyMappingFitEnumeration {
    
    /// <remarks/>
    Exact,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("CAPEC More Abstract")]
    CAPECMoreAbstract,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("CAPEC More Specific")]
    CAPECMoreSpecific,
    
    /// <remarks/>
    Imprecise,
    
    /// <remarks/>
    Perspective,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum TaxonomyNameEnumeration {
    
    /// <remarks/>
    ATTACK,
    
    /// <remarks/>
    WASC,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("OWASP Attacks")]
    OWASPAttacks,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class AlternateTermsTypeAlternate_Term {
    
    private string termField;
    
    private StructuredTextType descriptionField;
    
    /// <remarks/>
    public string Term {
        get {
            return this.termField;
        }
        set {
            this.termField = value;
        }
    }
    
    /// <remarks/>
    public StructuredTextType Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum LikelihoodEnumeration {
    
    /// <remarks/>
    High,
    
    /// <remarks/>
    Medium,
    
    /// <remarks/>
    Low,
    
    /// <remarks/>
    Unknown,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum SeverityEnumeration {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Very High")]
    VeryHigh,
    
    /// <remarks/>
    High,
    
    /// <remarks/>
    Medium,
    
    /// <remarks/>
    Low,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Very Low")]
    VeryLow,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class RelatedAttackPatternTypeRelated_Attack_Pattern {
    
    private ExcludeRelatedType[] exclude_RelatedField;
    
    private RelatedNatureEnumeration natureField;
    
    private string cAPEC_IDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Exclude_Related")]
    public ExcludeRelatedType[] Exclude_Related {
        get {
            return this.exclude_RelatedField;
        }
        set {
            this.exclude_RelatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public RelatedNatureEnumeration Nature {
        get {
            return this.natureField;
        }
        set {
            this.natureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string CAPEC_ID {
        get {
            return this.cAPEC_IDField;
        }
        set {
            this.cAPEC_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum RelatedNatureEnumeration {
    
    /// <remarks/>
    ChildOf,
    
    /// <remarks/>
    ParentOf,
    
    /// <remarks/>
    CanFollow,
    
    /// <remarks/>
    CanPrecede,
    
    /// <remarks/>
    CanAlsoBe,
    
    /// <remarks/>
    PeerOf,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class ExecutionFlowTypeAttack_Step {
    
    private string stepField;
    
    private ExecutionFlowTypeAttack_StepPhase phaseField;
    
    private StructuredTextType descriptionField;
    
    private ExecutionFlowTypeAttack_StepTechnique[] techniqueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Step {
        get {
            return this.stepField;
        }
        set {
            this.stepField = value;
        }
    }
    
    /// <remarks/>
    public ExecutionFlowTypeAttack_StepPhase Phase {
        get {
            return this.phaseField;
        }
        set {
            this.phaseField = value;
        }
    }
    
    /// <remarks/>
    public StructuredTextType Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Technique")]
    public ExecutionFlowTypeAttack_StepTechnique[] Technique {
        get {
            return this.techniqueField;
        }
        set {
            this.techniqueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public enum ExecutionFlowTypeAttack_StepPhase {
    
    /// <remarks/>
    Explore,
    
    /// <remarks/>
    Experiment,
    
    /// <remarks/>
    Exploit,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class ExecutionFlowTypeAttack_StepTechnique : StructuredTextType {
    
    private string cAPEC_IDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CAPEC_ID {
        get {
            return this.cAPEC_IDField;
        }
        set {
            this.cAPEC_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class SkillsTypeSkill {
    
    private SkillLevelEnumeration levelField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SkillLevelEnumeration Level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum SkillLevelEnumeration {
    
    /// <remarks/>
    High,
    
    /// <remarks/>
    Medium,
    
    /// <remarks/>
    Low,
    
    /// <remarks/>
    Unknown,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class ConsequencesTypeConsequence {
    
    private ScopeEnumeration[] scopeField;
    
    private TechnicalImpactEnumeration[] impactField;
    
    private LikelihoodEnumeration likelihoodField;
    
    private bool likelihoodFieldSpecified;
    
    private StructuredTextType noteField;
    
    private string consequence_IDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Scope")]
    public ScopeEnumeration[] Scope {
        get {
            return this.scopeField;
        }
        set {
            this.scopeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Impact")]
    public TechnicalImpactEnumeration[] Impact {
        get {
            return this.impactField;
        }
        set {
            this.impactField = value;
        }
    }
    
    /// <remarks/>
    public LikelihoodEnumeration Likelihood {
        get {
            return this.likelihoodField;
        }
        set {
            this.likelihoodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LikelihoodSpecified {
        get {
            return this.likelihoodFieldSpecified;
        }
        set {
            this.likelihoodFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public StructuredTextType Note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Consequence_ID {
        get {
            return this.consequence_IDField;
        }
        set {
            this.consequence_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum ScopeEnumeration {
    
    /// <remarks/>
    Confidentiality,
    
    /// <remarks/>
    Integrity,
    
    /// <remarks/>
    Availability,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Access Control")]
    AccessControl,
    
    /// <remarks/>
    Accountability,
    
    /// <remarks/>
    Authentication,
    
    /// <remarks/>
    Authorization,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Non-Repudiation")]
    NonRepudiation,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum TechnicalImpactEnumeration {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Modify Data")]
    ModifyData,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Read Data")]
    ReadData,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Unreliable Execution")]
    UnreliableExecution,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Resource Consumption")]
    ResourceConsumption,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Execute Unauthorized Commands")]
    ExecuteUnauthorizedCommands,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Gain Privileges")]
    GainPrivileges,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Bypass Protection Mechanism")]
    BypassProtectionMechanism,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Hide Activities")]
    HideActivities,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Alter Execution Logic")]
    AlterExecutionLogic,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://capec.mitre.org/capec-3")]
public class RelatedWeaknessesTypeRelated_Weakness {
    
    private string cWE_IDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string CWE_ID {
        get {
            return this.cWE_IDField;
        }
        set {
            this.cWE_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum AbstractionEnumeration {
    
    /// <remarks/>
    Meta,
    
    /// <remarks/>
    Standard,
    
    /// <remarks/>
    Detailed,
}
