//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.8.0.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace CVESearch.CveXmlJsonModels
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// CPE name
    /// </summary>    
    public class Def_cpe_name
    {
        [JsonProperty("cpe22Uri")]
        public string Cpe22Uri { get; set; }

        [JsonProperty("cpe23Uri", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string Cpe23Uri { get; set; }

        [JsonProperty("lastModifiedDate")]
        public string LastModifiedDate { get; set; }
    }

    /// <summary>
    /// CPE match string or range
    /// </summary>    
    public class Def_cpe_match
    {
        [JsonProperty("vulnerable", Required = Required.Always)]
        public bool Vulnerable { get; set; }

        [JsonProperty("cpe22Uri")]
        public string Cpe22Uri { get; set; }

        [JsonProperty("cpe23Uri", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string Cpe23Uri { get; set; }

        [JsonProperty("versionStartExcluding")]
        public string VersionStartExcluding { get; set; }

        [JsonProperty("versionStartIncluding")]
        public string VersionStartIncluding { get; set; }

        [JsonProperty("versionEndExcluding")]
        public string VersionEndExcluding { get; set; }

        [JsonProperty("versionEndIncluding")]
        public string VersionEndIncluding { get; set; }

        [JsonProperty("cpe_name")]
        public System.Collections.Generic.ICollection<Def_cpe_name> Cpe_name { get; set; }
    }

    /// <summary>
    /// Defines a node or sub-node in an NVD applicability statement.
    /// </summary>    
    public class Def_node
    {
        [JsonProperty("operator")]
        public string Operator { get; set; }

        [JsonProperty("negate")]
        public bool Negate { get; set; }

        [JsonProperty("children")]
        public System.Collections.Generic.ICollection<Def_node> Children { get; set; }

        [JsonProperty("cpe_match")]
        public System.Collections.Generic.ICollection<Def_cpe_match> Cpe_match { get; set; }
    }

    /// <summary>
    /// Defines the set of product configurations for a NVD applicability statement.
    /// </summary>
    
    public class Def_configurations
    {
        [JsonProperty("CVE_data_version", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string CVE_data_version { get; set; }

        [JsonProperty("nodes")]
        public System.Collections.Generic.ICollection<Def_node> Nodes { get; set; }
    }

    /// <summary>
    /// Impact scores for a vulnerability as found on NVD.
    /// </summary>
    
    public class Def_impact
    {
        /// <summary>
        /// CVSS V3.x score.
        /// </summary>
        [JsonProperty("baseMetricV3")]
        public BaseMetricV3 BaseMetricV3 { get; set; }

        /// <summary>
        /// CVSS V2.0 score.
        /// </summary>
        [JsonProperty("baseMetricV2")]
        public BaseMetricV2 BaseMetricV2 { get; set; }
    }

    /// <summary>
    /// Defines a vulnerability in the NVD data feed.
    /// </summary>
    
    public class Def_cve_item
    {
        [JsonProperty("cve", Required = Required.Always)]
        [Required]
        public Schema Cve { get; set; } = new Schema();

        [JsonProperty("configurations")]
        public Def_configurations Configurations { get; set; }

        [JsonProperty("impact")]
        public Def_impact Impact { get; set; }

        [JsonProperty("publishedDate")]
        public string PublishedDate { get; set; }

        [JsonProperty("lastModifiedDate")]
        public string LastModifiedDate { get; set; }
    }

    
    public enum AttackVectorType
    {

        [EnumMember(Value = @"NETWORK")]
        NETWORK = 0,


        [EnumMember(Value = @"ADJACENT_NETWORK")]
        ADJACENT_NETWORK = 1,


        [EnumMember(Value = @"LOCAL")]
        LOCAL = 2,


        [EnumMember(Value = @"PHYSICAL")]
        PHYSICAL = 3,


    }

    
    public enum ModifiedAttackVectorType
    {

        [EnumMember(Value = @"NETWORK")]
        NETWORK = 0,


        [EnumMember(Value = @"ADJACENT_NETWORK")]
        ADJACENT_NETWORK = 1,


        [EnumMember(Value = @"LOCAL")]
        LOCAL = 2,


        [EnumMember(Value = @"PHYSICAL")]
        PHYSICAL = 3,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 4,


    }

    
    public enum AttackComplexityType
    {

        [EnumMember(Value = @"HIGH")]
        HIGH = 0,


        [EnumMember(Value = @"LOW")]
        LOW = 1,


    }

    
    public enum ModifiedAttackComplexityType
    {

        [EnumMember(Value = @"HIGH")]
        HIGH = 0,


        [EnumMember(Value = @"LOW")]
        LOW = 1,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 2,


    }

    
    public enum PrivilegesRequiredType
    {

        [EnumMember(Value = @"HIGH")]
        HIGH = 0,


        [EnumMember(Value = @"LOW")]
        LOW = 1,


        [EnumMember(Value = @"NONE")]
        NONE = 2,


    }

    
    public enum ModifiedPrivilegesRequiredType
    {

        [EnumMember(Value = @"HIGH")]
        HIGH = 0,


        [EnumMember(Value = @"LOW")]
        LOW = 1,


        [EnumMember(Value = @"NONE")]
        NONE = 2,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 3,


    }

    
    public enum UserInteractionType
    {

        [EnumMember(Value = @"NONE")]
        NONE = 0,


        [EnumMember(Value = @"REQUIRED")]
        REQUIRED = 1,


    }

    
    public enum ModifiedUserInteractionType
    {

        [EnumMember(Value = @"NONE")]
        NONE = 0,


        [EnumMember(Value = @"REQUIRED")]
        REQUIRED = 1,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 2,


    }

    
    public enum ScopeType
    {

        [EnumMember(Value = @"UNCHANGED")]
        UNCHANGED = 0,


        [EnumMember(Value = @"CHANGED")]
        CHANGED = 1,


    }

    
    public enum ModifiedScopeType
    {

        [EnumMember(Value = @"UNCHANGED")]
        UNCHANGED = 0,


        [EnumMember(Value = @"CHANGED")]
        CHANGED = 1,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 2,


    }

    
    public enum CiaType
    {

        [EnumMember(Value = @"NONE")]
        NONE = 0,


        [EnumMember(Value = @"LOW")]
        LOW = 1,


        [EnumMember(Value = @"HIGH")]
        HIGH = 2,


    }

    
    public enum ModifiedCiaType
    {

        [EnumMember(Value = @"NONE")]
        NONE = 0,


        [EnumMember(Value = @"LOW")]
        LOW = 1,


        [EnumMember(Value = @"HIGH")]
        HIGH = 2,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 3,


    }

    
    public enum ExploitCodeMaturityType
    {

        [EnumMember(Value = @"UNPROVEN")]
        UNPROVEN = 0,


        [EnumMember(Value = @"PROOF_OF_CONCEPT")]
        PROOF_OF_CONCEPT = 1,


        [EnumMember(Value = @"FUNCTIONAL")]
        FUNCTIONAL = 2,


        [EnumMember(Value = @"HIGH")]
        HIGH = 3,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 4,


    }

    
    public enum RemediationLevelType
    {

        [EnumMember(Value = @"OFFICIAL_FIX")]
        OFFICIAL_FIX = 0,


        [EnumMember(Value = @"TEMPORARY_FIX")]
        TEMPORARY_FIX = 1,


        [EnumMember(Value = @"WORKAROUND")]
        WORKAROUND = 2,


        [EnumMember(Value = @"UNAVAILABLE")]
        UNAVAILABLE = 3,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 4,


    }

    
    public enum ConfidenceType
    {

        [EnumMember(Value = @"UNKNOWN")]
        UNKNOWN = 0,


        [EnumMember(Value = @"REASONABLE")]
        REASONABLE = 1,


        [EnumMember(Value = @"CONFIRMED")]
        CONFIRMED = 2,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 3,


    }

    
    public enum CiaRequirementType
    {

        [EnumMember(Value = @"LOW")]
        LOW = 0,


        [EnumMember(Value = @"MEDIUM")]
        MEDIUM = 1,


        [EnumMember(Value = @"HIGH")]
        HIGH = 2,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 3,


    }

    
    public enum SeverityType
    {

        [EnumMember(Value = @"NONE")]
        NONE = 0,


        [EnumMember(Value = @"LOW")]
        LOW = 1,


        [EnumMember(Value = @"MEDIUM")]
        MEDIUM = 2,


        [EnumMember(Value = @"HIGH")]
        HIGH = 3,


        [EnumMember(Value = @"CRITICAL")]
        CRITICAL = 4,


    }

    
    public class Json
    {
        /// <summary>
        /// CVSS Version
        /// </summary>
        [JsonProperty("version", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        [JsonConverter(typeof(StringEnumConverter))]
        public JsonVersion Version { get; set; }

        [JsonProperty("vectorString", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        [RegularExpression(@"^CVSS:3.[01]/((AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])/)*(AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$")]
        public string VectorString { get; set; }

        [JsonProperty("attackVector")]
        [JsonConverter(typeof(StringEnumConverter))]
        public AttackVectorType AttackVector { get; set; }

        [JsonProperty("attackComplexity")]
        [JsonConverter(typeof(StringEnumConverter))]
        public AttackComplexityType AttackComplexity { get; set; }

        [JsonProperty("privilegesRequired")]
        [JsonConverter(typeof(StringEnumConverter))]
        public PrivilegesRequiredType PrivilegesRequired { get; set; }

        [JsonProperty("userInteraction")]
        [JsonConverter(typeof(StringEnumConverter))]
        public UserInteractionType UserInteraction { get; set; }

        [JsonProperty("scope")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ScopeType Scope { get; set; }

        [JsonProperty("confidentialityImpact")]
        [JsonConverter(typeof(StringEnumConverter))]
        public CiaType ConfidentialityImpact { get; set; }

        [JsonProperty("integrityImpact")]
        [JsonConverter(typeof(StringEnumConverter))]
        public CiaType IntegrityImpact { get; set; }

        [JsonProperty("availabilityImpact")]
        [JsonConverter(typeof(StringEnumConverter))]
        public CiaType AvailabilityImpact { get; set; }

        [JsonProperty("baseScore", Required = Required.Always)]
        [Range(0D, 10D)]
        public double BaseScore { get; set; }

        [JsonProperty("baseSeverity", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        [JsonConverter(typeof(StringEnumConverter))]
        public SeverityType BaseSeverity { get; set; }

        [JsonProperty("exploitCodeMaturity")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ExploitCodeMaturityType ExploitCodeMaturity { get; set; }

        [JsonProperty("remediationLevel")]
        [JsonConverter(typeof(StringEnumConverter))]
        public RemediationLevelType RemediationLevel { get; set; }

        [JsonProperty("reportConfidence")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ConfidenceType ReportConfidence { get; set; }

        [JsonProperty("temporalScore")]
        [Range(0D, 10D)]
        public double TemporalScore { get; set; }

        [JsonProperty("temporalSeverity")]
        [JsonConverter(typeof(StringEnumConverter))]
        public SeverityType TemporalSeverity { get; set; }

        [JsonProperty("confidentialityRequirement")]
        [JsonConverter(typeof(StringEnumConverter))]
        public CiaRequirementType ConfidentialityRequirement { get; set; }

        [JsonProperty("integrityRequirement")]
        [JsonConverter(typeof(StringEnumConverter))]
        public CiaRequirementType IntegrityRequirement { get; set; }

        [JsonProperty("availabilityRequirement")]
        [JsonConverter(typeof(StringEnumConverter))]
        public CiaRequirementType AvailabilityRequirement { get; set; }

        [JsonProperty("modifiedAttackVector")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ModifiedAttackVectorType ModifiedAttackVector { get; set; }

        [JsonProperty("modifiedAttackComplexity")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ModifiedAttackComplexityType ModifiedAttackComplexity { get; set; }

        [JsonProperty("modifiedPrivilegesRequired")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ModifiedPrivilegesRequiredType ModifiedPrivilegesRequired { get; set; }

        [JsonProperty("modifiedUserInteraction")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ModifiedUserInteractionType ModifiedUserInteraction { get; set; }

        [JsonProperty("modifiedScope")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ModifiedScopeType ModifiedScope { get; set; }

        [JsonProperty("modifiedConfidentialityImpact")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ModifiedCiaType ModifiedConfidentialityImpact { get; set; }

        [JsonProperty("modifiedIntegrityImpact")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ModifiedCiaType ModifiedIntegrityImpact { get; set; }

        [JsonProperty("modifiedAvailabilityImpact")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ModifiedCiaType ModifiedAvailabilityImpact { get; set; }

        [JsonProperty("environmentalScore")]
        [Range(0D, 10D)]
        public double EnvironmentalScore { get; set; }

        [JsonProperty("environmentalSeverity")]
        [JsonConverter(typeof(StringEnumConverter))]
        public SeverityType EnvironmentalSeverity { get; set; }

    }

    
    public enum AccessVectorType
    {

        [EnumMember(Value = @"NETWORK")]
        NETWORK = 0,


        [EnumMember(Value = @"ADJACENT_NETWORK")]
        ADJACENT_NETWORK = 1,


        [EnumMember(Value = @"LOCAL")]
        LOCAL = 2,


    }

    
    public enum AccessComplexityType
    {

        [EnumMember(Value = @"HIGH")]
        HIGH = 0,


        [EnumMember(Value = @"MEDIUM")]
        MEDIUM = 1,


        [EnumMember(Value = @"LOW")]
        LOW = 2,


    }

    
    public enum AuthenticationType
    {

        [EnumMember(Value = @"MULTIPLE")]
        MULTIPLE = 0,


        [EnumMember(Value = @"SINGLE")]
        SINGLE = 1,


        [EnumMember(Value = @"NONE")]
        NONE = 2
    }

    
    public enum CiaType2
    {

        [EnumMember(Value = @"NONE")]
        NONE = 0,


        [EnumMember(Value = @"PARTIAL")]
        PARTIAL = 1,


        [EnumMember(Value = @"COMPLETE")]
        COMPLETE = 2
    }

    
    public enum ExploitabilityType
    {

        [EnumMember(Value = @"UNPROVEN")]
        UNPROVEN = 0,


        [EnumMember(Value = @"PROOF_OF_CONCEPT")]
        PROOF_OF_CONCEPT = 1,


        [EnumMember(Value = @"FUNCTIONAL")]
        FUNCTIONAL = 2,


        [EnumMember(Value = @"HIGH")]
        HIGH = 3,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 4
    }

    
    public enum RemediationLevelType2
    {

        [EnumMember(Value = @"OFFICIAL_FIX")]
        OFFICIAL_FIX = 0,


        [EnumMember(Value = @"TEMPORARY_FIX")]
        TEMPORARY_FIX = 1,


        [EnumMember(Value = @"WORKAROUND")]
        WORKAROUND = 2,


        [EnumMember(Value = @"UNAVAILABLE")]
        UNAVAILABLE = 3,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 4
    }

    
    public enum ReportConfidenceType
    {

        [EnumMember(Value = @"UNCONFIRMED")]
        UNCONFIRMED = 0,


        [EnumMember(Value = @"UNCORROBORATED")]
        UNCORROBORATED = 1,


        [EnumMember(Value = @"CONFIRMED")]
        CONFIRMED = 2,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 3
    }

    
    public enum CollateralDamagePotentialType
    {

        [EnumMember(Value = @"NONE")]
        NONE = 0,


        [EnumMember(Value = @"LOW")]
        LOW = 1,


        [EnumMember(Value = @"LOW_MEDIUM")]
        LOW_MEDIUM = 2,


        [EnumMember(Value = @"MEDIUM_HIGH")]
        MEDIUM_HIGH = 3,


        [EnumMember(Value = @"HIGH")]
        HIGH = 4,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 5
    }

    
    public enum TargetDistributionType
    {

        [EnumMember(Value = @"NONE")]
        NONE = 0,


        [EnumMember(Value = @"LOW")]
        LOW = 1,


        [EnumMember(Value = @"MEDIUM")]
        MEDIUM = 2,


        [EnumMember(Value = @"HIGH")]
        HIGH = 3,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 4,


    }

    
    public enum CiaRequirementType2
    {

        [EnumMember(Value = @"LOW")]
        LOW = 0,


        [EnumMember(Value = @"MEDIUM")]
        MEDIUM = 1,


        [EnumMember(Value = @"HIGH")]
        HIGH = 2,


        [EnumMember(Value = @"NOT_DEFINED")]
        NOT_DEFINED = 3,


    }

    
    public class Json2
    {
        /// <summary>
        /// CVSS Version
        /// </summary>
        [JsonProperty("version", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        [JsonConverter(typeof(StringEnumConverter))]
        public Json2Version Version { get; set; }

        [JsonProperty("vectorString", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        [RegularExpression(@"^((AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))/)*(AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))$")]
        public string VectorString { get; set; }

        [JsonProperty("accessVector")]
        [JsonConverter(typeof(StringEnumConverter))]
        public AccessVectorType AccessVector { get; set; }

        [JsonProperty("accessComplexity")]
        [JsonConverter(typeof(StringEnumConverter))]
        public AccessComplexityType AccessComplexity { get; set; }

        [JsonProperty("authentication")]
        [JsonConverter(typeof(StringEnumConverter))]
        public AuthenticationType Authentication { get; set; }

        [JsonProperty("confidentialityImpact")]
        [JsonConverter(typeof(StringEnumConverter))]
        public CiaType2 ConfidentialityImpact { get; set; }

        [JsonProperty("integrityImpact")]
        [JsonConverter(typeof(StringEnumConverter))]
        public CiaType2 IntegrityImpact { get; set; }

        [JsonProperty("availabilityImpact")]
        [JsonConverter(typeof(StringEnumConverter))]
        public CiaType2 AvailabilityImpact { get; set; }

        [JsonProperty("baseScore", Required = Required.Always)]
        [Range(0D, 10D)]
        public double BaseScore { get; set; }

        [JsonProperty("exploitability")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ExploitabilityType Exploitability { get; set; }

        [JsonProperty("remediationLevel")]
        [JsonConverter(typeof(StringEnumConverter))]
        public RemediationLevelType2 RemediationLevel { get; set; }

        [JsonProperty("reportConfidence")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ReportConfidenceType ReportConfidence { get; set; }

        [JsonProperty("temporalScore")]
        [Range(0D, 10D)]
        public double TemporalScore { get; set; }

        [JsonProperty("collateralDamagePotential")]
        [JsonConverter(typeof(StringEnumConverter))]
        public CollateralDamagePotentialType CollateralDamagePotential { get; set; }

        [JsonProperty("targetDistribution")]
        [JsonConverter(typeof(StringEnumConverter))]
        public TargetDistributionType TargetDistribution { get; set; }

        [JsonProperty("confidentialityRequirement")]
        [JsonConverter(typeof(StringEnumConverter))]
        public CiaRequirementType2 ConfidentialityRequirement { get; set; }

        [JsonProperty("integrityRequirement")]
        [JsonConverter(typeof(StringEnumConverter))]
        public CiaRequirementType2 IntegrityRequirement { get; set; }

        [JsonProperty("availabilityRequirement")]
        [JsonConverter(typeof(StringEnumConverter))]
        public CiaRequirementType2 AvailabilityRequirement { get; set; }

        [JsonProperty("environmentalScore")]
        [Range(0D, 10D)]
        public double EnvironmentalScore { get; set; }

    }

    
    public class Product
    {
        [JsonProperty("product_name", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string Product_name { get; set; }

        [JsonProperty("version", Required = Required.Always)]
        [Required]
        public Version Version { get; set; } = new Version();

    }

    
    public class Reference
    {
        [JsonProperty("url", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        [StringLength(500)]
        [RegularExpression(@"^(ftp|http)s?://\S+$")]
        public string Url { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("refsource")]
        public string Refsource { get; set; }

        [JsonProperty("tags")]
        public System.Collections.Generic.ICollection<string> Tags { get; set; }

    }

    
    public class Lang_string
    {
        [JsonProperty("lang", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string Lang { get; set; }

        [JsonProperty("value", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        [StringLength(3999)]
        public string Value { get; set; }


    }

    
    public class Schema
    {
        [JsonProperty("data_type", Required = Required.Always)]
        public SchemaData_type Data_type { get; set; }

        [JsonProperty("data_format", Required = Required.Always)]
        public SchemaData_format Data_format { get; set; }

        [JsonProperty("data_version", Required = Required.Always)]
        public SchemaData_version Data_version { get; set; }

        [JsonProperty("CVE_data_meta", Required = Required.Always)]
        [Required]
        public CVE_data_meta CVE_data_meta { get; set; } = new CVE_data_meta();

        [JsonProperty("affects")]
        public Affects Affects { get; set; }

        [JsonProperty("problemtype", Required = Required.Always)]
        [Required]
        public Problemtype Problemtype { get; set; } = new Problemtype();

        [JsonProperty("references", Required = Required.Always)]
        [Required]
        public References References { get; set; } = new References();

        [JsonProperty("description", Required = Required.Always)]
        [Required]
        public Description Description { get; set; } = new Description();

    }

    
    public class Schema2
    {
        [JsonProperty("CVE_data_type", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string CVE_data_type { get; set; }

        [JsonProperty("CVE_data_format", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string CVE_data_format { get; set; }

        [JsonProperty("CVE_data_version", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string CVE_data_version { get; set; }

        /// <summary>
        /// NVD adds number of CVE in this feed
        /// </summary>
        [JsonProperty("CVE_data_numberOfCVEs")]
        public string CVE_data_numberOfCVEs { get; set; }

        /// <summary>
        /// NVD adds feed date timestamp
        /// </summary>
        [JsonProperty("CVE_data_timestamp")]
        public string CVE_data_timestamp { get; set; }

        /// <summary>
        /// NVD feed array of CVE
        /// </summary>
        [JsonProperty("CVE_Items", Required = Required.Always)]
        [Required]
        public System.Collections.Generic.ICollection<Def_cve_item> CVE_Items { get; set; } = new System.Collections.ObjectModel.Collection<Def_cve_item>();

    }

    
    public class BaseMetricV3
    {
        [JsonProperty("cvssV3")]
        public Json CvssV3 { get; set; }

        [JsonProperty("exploitabilityScore")]
        [Range(0D, 10D)]
        public double ExploitabilityScore { get; set; }

        [JsonProperty("impactScore")]
        [Range(0D, 10D)]
        public double ImpactScore { get; set; }
    }

    
    public class BaseMetricV2
    {
        [JsonProperty("cvssV2")]
        public Json2 CvssV2 { get; set; }

        [JsonProperty("severity")]
        public string Severity { get; set; }

        [JsonProperty("exploitabilityScore")]
        [Range(0D, 10D)]
        public double ExploitabilityScore { get; set; }

        [JsonProperty("impactScore")]
        [Range(0D, 10D)]
        public double ImpactScore { get; set; }

        [JsonProperty("acInsufInfo")]
        public bool AcInsufInfo { get; set; }

        [JsonProperty("obtainAllPrivilege")]
        public bool ObtainAllPrivilege { get; set; }

        [JsonProperty("obtainUserPrivilege")]
        public bool ObtainUserPrivilege { get; set; }

        [JsonProperty("obtainOtherPrivilege")]
        public bool ObtainOtherPrivilege { get; set; }

        [JsonProperty("userInteractionRequired")]
        public bool UserInteractionRequired { get; set; }
    }

    
    public enum JsonVersion
    {

        [EnumMember(Value = @"3.0")]
        _3_0 = 0,


        [EnumMember(Value = @"3.1")]
        _3_1 = 1,


    }

    
    public enum Json2Version
    {

        [EnumMember(Value = @"2.0")]
        _2_0 = 0,


    }

    
    public class Version
    {
        [JsonProperty("version_data", Required = Required.Always)]
        [Required]
        [MinLength(1)]
        public System.Collections.Generic.ICollection<Version_data> Version_data { get; set; } = new System.Collections.ObjectModel.Collection<Version_data>();

    }

    
    public enum SchemaData_type
    {

        [EnumMember(Value = @"CVE")]
        CVE = 0,


    }

    
    public enum SchemaData_format
    {

        [EnumMember(Value = @"MITRE")]
        MITRE = 0,


    }

    
    public enum SchemaData_version
    {

        [EnumMember(Value = @"4.0")]
        _4_0 = 0,


    }

    
    public class CVE_data_meta
    {
        [JsonProperty("ID", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        [RegularExpression(@"^CVE-[0-9]{4}-[0-9]{4,}$")]
        public string ID { get; set; }

        [JsonProperty("ASSIGNER", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$")]
        public string ASSIGNER { get; set; }

        [JsonProperty("STATE")]
        public string STATE { get; set; }

    }

    
    public class Affects
    {
        [JsonProperty("vendor", Required = Required.Always)]
        [Required]
        public Vendor Vendor { get; set; } = new Vendor();

    }

    
    public class Problemtype
    {
        [JsonProperty("problemtype_data", Required = Required.Always)]
        [Required]
        public System.Collections.Generic.ICollection<Problemtype_data> Problemtype_data { get; set; } = new System.Collections.ObjectModel.Collection<Problemtype_data>();

    }

    
    public class References
    {
        [JsonProperty("reference_data", Required = Required.Always)]
        [Required]
        [MaxLength(500)]
        public System.Collections.Generic.ICollection<Reference> Reference_data { get; set; } = new System.Collections.ObjectModel.Collection<Reference>();

    }

    
    public class Description
    {
        [JsonProperty("description_data", Required = Required.Always)]
        [Required]
        public System.Collections.Generic.ICollection<Lang_string> Description_data { get; set; } = new System.Collections.ObjectModel.Collection<Lang_string>();

    }

    
    public class Version_data
    {
        [JsonProperty("version_value", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string Version_value { get; set; }

        [JsonProperty("version_affected")]
        public string Version_affected { get; set; }

    }

    
    public class Vendor
    {
        [JsonProperty("vendor_data", Required = Required.Always)]
        [Required]
        public System.Collections.Generic.ICollection<Vendor_data> Vendor_data { get; set; } = new System.Collections.ObjectModel.Collection<Vendor_data>();


    }

    
    public class Problemtype_data
    {
        [JsonProperty("description", Required = Required.Always)]
        [Required]
        public System.Collections.Generic.ICollection<Lang_string> Description { get; set; } = new System.Collections.ObjectModel.Collection<Lang_string>();
    }

    
    public class Vendor_data
    {
        [JsonProperty("vendor_name", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string Vendor_name { get; set; }

        [JsonProperty("product", Required = Required.Always)]
        [Required]
        public Product2 Product { get; set; } = new Product2();
    }

    
    public class Product2
    {
        [JsonProperty("product_data", Required = Required.Always)]
        [Required]
        [MinLength(1)]
        public System.Collections.Generic.ICollection<Product> Product_data { get; set; } = new System.Collections.ObjectModel.Collection<Product>();
    }
}